### ISSUE TITLE
GrandExchange querying

### ISSUE THREAD

**Issue by PureCS** [EtherealLabs/osbot-scripts#12]

**Comment by drewlindsey** [comment]
This would be great as a lib. There's nothing like this on osbot is there?

**Comment by PureCS** [comment]
it cant pull prices i think, we should use the rsbuddy api since its simple  
the only issue is you cant use external libraries along with osbot? so we would need write our own small json parser rather than use a fully tested/developed one  
api url: https://api.rsbuddy.com/grandExchange?a=guidePrice&i={item id}

**Comment by PureCS** [comment]
I have written this, waiting for the bot to be back up so i can test it in action.
